name: CI/CD Apprentice 1
run-name: ${{ github.actor }} started GitHub Actions ğŸš€
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: node --version
      - run: npm --version
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: npm install
      - run: npm run compile
      - run: npm test
      - run: npm run build
      - run: echo "ğŸ This job's status is ${{ job.status }}."
